number = str(input('Enter a number: '))
print('Analysing the number {}'.format(number))
print('Unit:{}'.format(number[len(number)-1]))
number = number.replace(number[len(number)-1], '')
print('Dezena:{}'.format(number[len(number)-1]))
number = number.replace(number[len(number)-1], '')
print('Centena:{}'.format(number[len(number)-1]))
number = number.replace(number[len(number)-1], '')
print('Milhar:{}'.format(number[len(number)-1]))
number = number.replace(number[len(number)-1], '')